### ISSUE TITLE
todo's na demo overleg

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#89]
aantekeningen overleg: https://wiki.surfnet.nl/display/laexperiment/LA+overleg+4+mei

- [x] bestaande weeknummers en onderwerpen als linkje tonen bij het aanmaken van een nieuw recept
- [x] filter aanzetten voor formatieve toetsen
- [x] link naar informatie aanpassen op de homepage, link is: https://wiki.surfnet.nl/display/laexperiment
- [x] onze `<img>` tag afsluiten met een &
- [x] download data aanvullen met nieuwe kolommen
- [ ] nieuwe button: '+ answer' & vereenvoudigen integratie
- [ ] nieuwe versie toestemmingsverklaring
